#!/bin/sh
# Copyright (c) 2008 by Xuggle Inc. All rights reserved.
#
# It is REQUESTED BUT NOT REQUIRED if you use this library, that you let 
# us know by sending e-mail to info\@xuggle.com telling us briefly how you're
# using the library and what you like or don't like about it.
#
# This library is free software; you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License as published by the Free Software
# Foundation; either version 2.1 of the License, or (at your option) any later
# version.
#
# This library is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License along
# with this library; if not, write to the Free Software Foundation, Inc.,
# 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
# This file contains global rules that all Makefiles should know about.
# It should NOT be generated by AutoMake, but should be generated by Autoconf

# It requires a bash-compliant shell to be installed in order to work.
# We do this instead of ant's <copy/> task to deal with native code
# on windows; drive-letters (e.g. C:) causes havoc with the native builds,
# but get translated by it into Msys/Cygwin standard drive letters, which
# then won't work with <copy/>
STAGEDIR="$1"
DESTDIR="$2"
echo "Installing $STAGEDIR/* to $DESTDIR"
cp -rf "$STAGEDIR"/* $DESTDIR
